### ISSUE TITLE
Update some Wiki information

### ISSUE THREAD

**Issue by llvieira** [HewlettPackard/hpe-oneview-hubot#118]
Hi guys,

I noticed that the **Wiki** probably need some updates.

- Update  _Getting Started for Developers_ section:
Currently, to install **Node.js** and **npm** the command `sudo apt-get install -y nodejs` it's sufficient for both.

- Update Docker details ([https://hub.docker.com/r/hewlettpackardenterprise/hpe-oneview-hubot/](https://hub.docker.com/r/hewlettpackardenterprise/hpe-oneview-hubot/)):
Always that I run the Docker command [`docker run -it --rm -e HUBOT_NAME=$HUBOT_NAME -e "PARMS=-a slack" -e http_proxy=$http_proxy -e https_proxy=$https_proxy -e no_proxy=$no_proxy -e "HUBOT_SLACK_TOKEN=$HUBOT_SLACK_TOKEN"  -e HUBOT_LOG_LEVEL=DEBUG -v $(pwd)/oneview-configuration.json:/home/docker/hpe-oneview-hubot/oneview-configuration.json docker.io/hewlettpackardenterprise/hpe-oneview-hubot:latest`], it's necessary run it as a super user, otherwise a Docker error is raised, and I do not find out this information there.

My best regards!

**Comment by danielreed** [comment]
Thanks I've made the documentation changes.
