### ISSUE TITLE
Problem with some npm dependencies when I start hubot

### ISSUE THREAD

**Issue by llvieira** [HewlettPackard/hpe-oneview-hubot#119]
Hi guys,

After I do almost all process described on [Wiki](https://github.com/HewlettPackard/hpe-oneview-hubot/wiki/Getting-Started-for-Developers) to start developing, when I go to run the **hubot** some **npm** errors showing missing dependencies is raised.

Only after I install all the following dependencies on hubot directory, I can start it successfully.

```
nlp_compromise
fuzzyset.js
d3
jsdom
svg2png
hubot-conversation
request-promise
amqp
```

Some idea about this problem?
My best regards!

**Comment by danielreed** [comment]
Yes you will have to install the project's dependencies in hubot directory before it can start successfully.  Step 8 in the WIKI should cover that.  The 'npm install' in that step should use the dependencies listed in the projects package.json.

**Comment by llvieira** [comment]
On the **Step 8** in the [Wiki](https://github.com/HewlettPackard/hpe-oneview-hubot/wiki/Getting-Started-for-Developers) you need to change `npm install` to `npm install ../hpe-oneview-hubot/`.

**Comment by danielreed** [comment]
Good catch! I've update the WIKI.
