### ISSUE TITLE
NLP middleware layer is stripping words needed by the regexs in the listeners

### ISSUE THREAD

**Issue by danielreed** [HewlettPackard/hpe-oneview-hubot#14]
The lexer seems to be stripping words that are needed by the regexs in the individual listeners. So @hubot list all server profiles becomes @hubot list all server causing the regex not to match in the listener.

**Comment by jesseolsen** [comment]
I was not able to reproduce the issue with "list all server profiles"

**Comment by llvieira** [comment]
Hi @danielreed, can you still reproduce this issue? Or is it already fixed?

**Comment by danielreed** [comment]
@llvieira I think we can probably close this issue now.  It doesn't seem to be an issue any longer.
