### ISSUE TITLE
Docker - /go.sh: line 11: jq: command not found

### ISSUE THREAD

**Issue by andrewrmoore** [HewlettPackard/hpe-oneview-hubot#151]
When running the Docker container pulled from `hewlettpackardenterprise/hpe-oneview-hubot:latest` the following error is displayed in the log:

> /go.sh: line 11: jq: command not found

Because of this it then later fails as there is no content in /home/docker/hubot/oneview-configuration.json

Any help would be appreciated.

**Comment by danielreed** [comment]
Hey @andrewrmoore it looks like I broke this. I think the fix will be simple, I'll see if I can make it soon.  Thanks for opening this issue.
