### ISSUE TITLE
The oneview-configuration file needs to support chat room definition

### ISSUE THREAD

**Issue by danielreed** [HewlettPackard/hpe-oneview-hubot#18]
Currently notifications are delivered to a chat room that is hard-coded in the ov-listener class. This needs to be changed so that it is loaded from the oneview-configuration.json file. A new property needs to be added to that json file:

"chatRoom": "room-name"

**Comment by jesseolsen** [comment]
calling it:
"notificationsRoom": "room-name"
because it is the room that notifications will go to.  They may want to chat with the bot in a different room.

**Comment by jesseolsen** [comment]
done
