### ISSUE TITLE
How to support pagination in chat?

### ISSUE THREAD

**Issue by danielreed** [HewlettPackard/hpe-oneview-hubot#2]
We cannot echo 600 server hardware when someone says list all.  Whats the max? How does the user get more?

![sh-all-answer](https://cloud.githubusercontent.com/assets/901134/20277798/4d2efe34-aa5f-11e6-87e9-b03a5c0ed15a.PNG)

**Comment by llvieira** [comment]
I'm working on it. Now when the user says list all, the resources will be listed in parts of 10.
