### ISSUE TITLE
Create default listener when other listeners don't respond

### ISSUE THREAD

**Issue by danielreed** [HewlettPackard/hpe-oneview-hubot#20]
Need a default listener that will respond when the other listeners do not. Listener should return a list of bot's capabilities. It looks like robot.catchAll might work for this.

**Comment by gregfuruiye** [comment]
Does the listener need to return a list of capabilities? An alternative may be to ask a question that helps refine requests. For example:

"Hmmm. Not sure I quite got that. Maybe give some more details and we'll see what I can come up with?"

Whatever the case, we can match it with the persona of the bot.

**Comment by danielreed** [comment]
I think this could be related to the work/discussion for issue 15.  If we can figure out how to handle the UX for issue 15 I think we can use that here.

**Comment by danielreed** [comment]
Done.
