### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by danielreed** [HewlettPackard/hpe-oneview-hubot#27]
Need to improve the error handling so that OneView errors are displayed nicely and not as large JSON strings.  Might need some UX here to determine which fields on the OV error should be shown.

**Comment by gregfuruiye** [comment]
This is going to expose my lack on JSON knowledge. @danielreed, what does the JSON string look like? Ideally, we present errors in the same way as we do in OneView.

**Comment by jesseolsen** [comment]
@gregfuruiye -- Depends on the error.  Here's an error when trying to connect to a bad IP:
{
  "name": "RequestError",
  "message": "Error: connect EHOSTUNREACH 192.168.55.90:55550",
  "cause": {
    "code": "EHOSTUNREACH",
    "errno": "EHOSTUNREACH",
    "syscall": "connect",
    "address": "192.168.55.90",
    "port": 55550
  },
  "error": {
    "code": "EHOSTUNREACH",
    "errno": "EHOSTUNREACH",
    "syscall": "connect",
    "address": "192.168.55.90",
    "port": 55550
  },
  "options": {
    "method": "GET",
    "uri": "http://192.168.55.90:55550/inventory",
    "json": true,
    "headers": {
      "Accept": "application/json",
      "Content-Type": "application/json"
    },
    "resolveWithFullResponse": true,
    "simple": true,
    "transform2xxOnly": false
  }
}

**Comment by danielreed** [comment]
I think at the very least we should inspect the OV error response body to determine what we want to show the user.  We don't have a lot of space to display all of the error information, but maybe we should display:

statusCode, errorCode, message, and recommendedActions

This is what the response body looks like from OV:

"response": {
    "statusCode": 404,
    "body": {
      "details": "",
      "errorSource": null,
      "nestedErrors": [],
      "recommendedActions": [
        "Verify that the profile exists and try again."
      ],
      "errorCode": "ProfileNotFoundException",
      "data": {},
      "message": "The requested profile cannot be retrieved  [id=fdb4be1d]."
    }
}
