### ISSUE TITLE
Add support for HipChat

### ISSUE THREAD

**Issue by jesseolsen** [HewlettPackard/hpe-oneview-hubot#34]
Add support for HipChat: https://www.hipchat.com/

**Comment by jesseolsen** [comment]
Got it working locally...  After some internal feedback, I'll put up a Pull Request...

**Comment by danielreed** [comment]
Jesse the HipChat integration is looking good.  But the bot is returning large JSON strings.  The JSON needs to be formatted like the Slack transformer does.  We don't want to return the OV JSON payload to the user.

**Comment by danielreed** [comment]
I think this is probably complete now.
