### ISSUE TITLE
hubot - slack integration

### ISSUE THREAD

**Issue by reddypramod85** [HewlettPackard/hpe-oneview-hubot#39]
when i issue HUBOT_ADAPTER=slack HUBOT_SLACK_TOKEN=*****  ./bin/hubot
getting below error

info: unable to RTM start, attempting reconnect: Error: self signed certificate

but when i give ./bin/hubot then it's working fine
@hubot list all server hardware
getting the JSON response.

$ node --version
v7.2.0
$ npm --version
3.10.9

**Comment by danielreed** [comment]
@reddypramod85 are you connecting to Slack from behind a proxy?

**Comment by reddypramod85** [comment]
Connected from HPE network

**Comment by danielreed** [comment]
Does your Hubot instance without this plugin connect to Slack successfully?

**Comment by reddypramod85** [comment]
@danielreed 
I tried Hubot instance without this plugin and the connection was unsuccessful. But when I logged in from Home network I was able to connect to slack. Can you please help me with work around for proxy?

**Comment by danielreed** [comment]
You probably need to set http_proxy and https_proxy variables in the shell where you are starting Hubot.  You’ll need to use the correct proxy host for the network you are on.

**Comment by reddypramod85** [comment]
@danielreed 
Thanks you Daniel, after setting the proxy able to list all server hardware from slack channel.

**Comment by danielreed** [comment]
Ok that's great news.  I'm going to close this issue.
