### ISSUE TITLE
TLS Backoff

### ISSUE THREAD

**Issue by danielreed** [HewlettPackard/hpe-oneview-hubot#5]
We need to figure out a cleaner way to avoid HTTPS/TLS errors when communicating with our management station.  The current implementation affects TLS for the entire Hubot server, this setting would let us get MITM and we would never know.

```js
//TODO this is global to the NodeJS process we probably want to figure out a cleaner way to do this
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```

**Comment by llvieira** [comment]
@danielreed I searched in many places and I figure out a better detailed solution to this problem, but still it is a **less insecure** way to fix it.

We can see it here: https://stackoverflow.com/questions/20433287/node-js-request-cert-has-expired#answer-29397100

I don't know how good this solution is for us, but `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` it's really bad.

**Comment by danielreed** [comment]
@llvieira the solution you posted looks like the thing we want to do.  It doesn't look terribly difficult.  I think the changes to the Connection class to make this work would be pretty small.  Thanks for posting a solution.
