### ISSUE TITLE
Resources using JSON fields for titles, should use title capitalization instead

### ISSUE THREAD

**Issue by danielreed** [HewlettPackard/hpe-oneview-hubot#58]
All of the resources are showing the JSON field names for titles, instead the titles should use title capitalization instead.  So formFactor should become Form Factor.

![sh-capture](https://cloud.githubusercontent.com/assets/901134/24465454/4a2b8c64-146a-11e7-9525-6eb9a5d2ec3f.PNG)

**Comment by jonmccormick** [comment]
I'm working on this.

**Comment by danielreed** [comment]
Going to leave this open until we get some tests to cover the Resource class.

**Comment by jonmccormick** [comment]
Complete with units

**Comment by jonmccormick** [comment]
Need to do the same for HipChat.  Also fix alert.js to do it as well.
